version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - .env  
    volumes:
      - ./backend:/app

  frontend:
    build: ./client
    ports:
      - "5173:80"
    environment:
      - BACKEND_URL=http://backend:3000 
    depends_on:
      - backend
