# Verwende ein neueres Node.js Basisimage
FROM node:lts-alpine

# Setze das Arbeitsverzeichnis
WORKDIR /usr/src/app

# Kopiere package.json und package-lock.json
COPY api/package*.json ./

# Installiere Abhängigkeiten und baue native Module neu
RUN npm install 

# Kopiere Anwendungscode
COPY api/ .


# Exponiere den Port
EXPOSE 5000

# Startbefehl für die Anwendung
CMD ["node", "index.js"]







