# docker-compose.yml
version: "3.8"
services:
  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=https://docker.compose.local/

  backend:
    build: ./api
    ports:
      - "3000:3000"

  proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend