version: '3.8'

services:
  backend:
    build: ./api
    ports:
      - "3000:3000"
    env_file:
      - api/.env  
    volumes:
      - ./api:/app  

  frontend:
    build: ./client
    ports:
      - "5173:80"
    env_file:
      - client/.env  
    environment:
      - BACKEND_URL=http://backend:3000
    depends_on:
      - backend
