apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: estate-agent
    tier: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

