apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: combined-cluster
  region: eu-central-1

vpc:
  subnets:
    private:
      eu-central-1a: { id: subnet-0bb9c6005949e15f8 }
      eu-central-1b: { id: subnet-0a3d6393f9508d390 }

nodeGroups:
  - name: ng-1-workers
    labels: { role: workers }
    instanceType: m5.xlarge
    desiredCapacity: 10
    privateNetworking: true

  - name: ng-2-builders
    labels: { role: builders }
    instanceType: m5.2xlarge
    desiredCapacity: 2
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true



