apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: estate-agent
  namespace: default
spec:
  project: default
  source:
    repoURL: 'https://github.com/final-project-blog/estate-agent.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
