apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-deployment
      tier: frontend   
  template:
    metadata:
      labels:
        app: frontend-deployment
        tier: frontend   
    spec:
      containers:
        - name: frontend
          image: nourajaz/frontend-image:latest
          ports:
            - containerPort: 80