apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: estate-agent
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: estate-agent
      tier: backend
  template:
    metadata:
      labels:
        app: estate-agent
        tier: backend
    spec:
      containers:
        - name: backend
          image: nourajaz/backend-image:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://engahmadalebrahim:HoBt5fShJm7jycY6@estate-agent.6f9v6zh.mongodb.net/?retryWrites=true&w=majority&appName=estate-agent"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret

