apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server
  namespace: default
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter:9100']

      - job_name: 'api-estate-agent-backend'
        static_configs:
          - targets: ['api-estate-agent-backend:3000']

