name: CI/CD Pipeline
on: [push]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: deploy-backend
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        cd api
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.NGINX_EC2 }} "
          sudo yum update -y
          sudo yum install -y docker
          sudo systemctl start docker
          sudo docker stop backend-container || true
          sudo docker rm backend-container || true
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend:1.0.2 &&
          sudo docker run -d --network host --name backend-container ${{ secrets.DOCKER_USERNAME }}/backend:1.0.2
          sudo docker images --filter 'dangling=true' --format '{{.ID}}' | xargs -r sudo docker rmi -f
        "