name: CI/CD Pipeline
on: [push]
jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create env file
      run: |
        echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> api/.env
        echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> api/.env
        echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> api/.env
        echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> api/.env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> api/.env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> api/.env
        echo "AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}" >> api/.env
        echo "AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}" >> api/.env
        echo "AWS_BUCKET_REGION=${{ secrets.AWS_REGION }}" >> api/.env
        echo "PORT=${{ secrets.PORT }}" >> api/.env
    - name:  build backend docker image
      run: |
        docker build -t backend:1.0.0 ./api
    - name: Loggen uns im Docker Hub ein
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push backend docker image
      run: |
        docker tag backend:1.0.0 ${{ secrets.DOCKER_USERNAME }}/backend:1.0.0
        docker push ${{ secrets.DOCKER_USERNAME }}/backend:1.0.0
    - name: deploy-backend
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa | 
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.BACKEND_HOST }} "
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo docker stop backend-container
          sudo docker rm backend-container
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/backend:1.0.0 &&
          sudo docker run -d -p 3000:3000 --name backend-container ${{ secrets.DOCKER_USERNAME }}/backend:1.0.0
          sudo docker images --filter 'dangling=true' --format '{{.ID}}' | xargs -r sudo docker rmi -f
        "
  build-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name:  build frontend docker image
      run: |
        docker build -t frontend:1.0.0 ./client
    - name: Loggen uns im Docker Hub ein
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Push frontend docker image
      run: |
        docker tag frontend:1.0.0 ${{ secrets.DOCKER_USERNAME }}/frontend:1.0.0
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend:1.0.0
    - name: deploy-frontend
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa | 
        chmod 600 ~/.ssh/id_rsa
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.USERNAME }}@${{ secrets.FRONTEND_HOST }} "
          sudo yum update -y
          sudo yum install -y docker
          sudo service docker start
          sudo docker stop frontend-container
          sudo docker rm frontend-container
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/frontend:1.0.0 &&
          sudo docker run -d -p 4000:80 --name frontend-container ${{ secrets.DOCKER_USERNAME }}/frontend:1.0.0
          sudo docker images --filter 'dangling=true' --format '{{.ID}}' | xargs -r sudo docker rmi -f
        "